//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysioWebPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exercis()
        {
            this.ExerciseVideos = new HashSet<ExerciseVideo>();
            this.PrescribedExercises = new HashSet<PrescribedExercis>();
        }
    
        public int ExId { get; set; }
        public string ExName { get; set; }
        public string ExNameMandarin { get; set; }
        public string ExNameMalay { get; set; }
        public string ExNameTamil { get; set; }
        public string ExDescription { get; set; }
        public int ExSetNo { get; set; }
        public int ExRepNo { get; set; }
        public int ExTimePerDay { get; set; }
        public string ExAngleMeasureType { get; set; }
        public Nullable<double> ExAngleStandingPose { get; set; }
        public Nullable<double> ExAngleLyingPose { get; set; }
        public Nullable<double> ExHoldDuration { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExerciseVideo> ExerciseVideos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescribedExercis> PrescribedExercises { get; set; }
    }
}
