//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysioWebPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExerciseVideo
    {
        public int VId { get; set; }
        public int ExId { get; set; }
        public string VFileEnglish { get; set; }
        public string VFileMandarin { get; set; }
        public string VFileMalay { get; set; }
        public string VFileTamil { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
        public string VThumbnail { get; set; }
    
        public virtual Exercis Exercis { get; set; }
    }
}
