//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysioWebPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientCaregiver
    {
        public string PatientId { get; set; }
        public string CaregiverId { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
