//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysioWebPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformedExercis
    {
        public int PerformExId { get; set; }
        public int PEId { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int ExSetNo { get; set; }
        public int ExRepNo { get; set; }
        public int ExType { get; set; }
        public double AvgAngle { get; set; }
        public Nullable<double> AvgHoldDuration { get; set; }
        public string ExVisualFile { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
        public int Score { get; set; }
    
        public virtual PrescribedExercis PrescribedExercis { get; set; }
    }
}
