//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysioWebPortal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PHYSIODBEntities : DbContext
    {
        public PHYSIODBEntities()
            : base("name=PHYSIODBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<ExerciseVideo> ExerciseVideos { get; set; }
        public virtual DbSet<PatientCaregiver> PatientCaregivers { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<PerformedExercis> PerformedExercises { get; set; }
        public virtual DbSet<PrescribedExercis> PrescribedExercises { get; set; }
        public virtual DbSet<GiftReceived> GiftReceiveds { get; set; }
        public virtual DbSet<Gift> Gifts { get; set; }
        public virtual DbSet<HospitalStay> HospitalStays { get; set; }
        public virtual DbSet<Exercis> Exercises { get; set; }
    }
}
