//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysioWebPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescribedExercis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrescribedExercis()
        {
            this.PerformedExercises = new HashSet<PerformedExercis>();
        }
    
        public int PEId { get; set; }
        public int StayId { get; set; }
        public int ExId { get; set; }
        public System.DateTime AssignedDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int ExSetNo { get; set; }
        public int ExRepNo { get; set; }
        public int ExTimePerDay { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerformedExercis> PerformedExercises { get; set; }
        public virtual HospitalStay HospitalStay { get; set; }
        public virtual Exercis Exercis { get; set; }
    }
}
